spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        - id: UserAndClassManagementServiceInstructor
          uri: lb://UserAndClassManagementService
          predicates:
            - Path=/api/v1/instructor/**
        - id: UserAndClassManagementServiceStudent
          uri: lb://UserAndClassManagementService
          predicates:
            - Path=/api/v1/student/**
        - id: UserAndClassManagementServiceClass
          uri: lb://UserAndClassManagementService
          predicates:
            - Path=/api/v1/class/**

        - id: PaymentService
          uri: lb://PaymentService
          predicates:
            - Path=/api/v1/payment/**

        - id: AuthService
          uri: lb://AuthService
          predicates:
            - Path=/api/v1/auth/**

        - id: DiscoveryServer
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: DiscoveryServer-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
