spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        - id: UserAndClassManagementService
          uri: lb://UserAndClassManagementService
          predicates:
            - Path=/api/v1/user/**
            - Path=/api/v1/class/**
          filters:
            - SetPath=/
          metadata:
            cors:
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: "*"
              maxAge: 3600

        - id: AuthService
          uri: lb://AuthService
          predicates:
            - Path=/api/v1/auth/**
          metadata:
            cors:
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: "*"
              maxAge: 3600

        - id: DiscoveryServer
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
          metadata:
            cors:
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: "*"
              maxAge: 3600

        - id: DiscoveryServer-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
          metadata:
            cors:
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: "*"
              maxAge: 3600

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            maxAge: 3600

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true